version: '3'
services:
  coral-mysql80:
    image: mysql:8.0
    container_name: coral-mysql
    ports:
      - "3301:3306"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/init-sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: coral123456
    restart: always

  coral:
    build:
      context: coral-fe
      dockerfile: Dockerfile
    container_name: coral-fe
    ports:
      - "8106:8080"
    volumes:
      - ./coral/storage:/storage
      - ./coral/logs:/logs
      - ./coral/backup:/backup
      - /etc/localtime:/etc/localtime
    depends_on:
      - coral-mysql80
    restart: always